interval: 60s
output_mode: both
output_path: /var/lib/vm-metric-agent/samples.jsonl
root_path: /
metadata_url: http://169.254.169.254/openstack/latest/meta_data.json
gnocchi:
  endpoint: http://192.168.0.102:8041
  username: admin
  password: ""
  archive_policy_name: vm_guest_usage_default
network_exclude_prefixes:
  - lo
  - veth
  - cni
  - flannel
  - cilium
  - docker
  - br-
disk_exclude_prefixes:
  - loop
  - ram
  - fd
  - sr
